language: node_js
node_js:
  - "8.9.4"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - echo $ssh_key >> $HOME/.ssh/known_hosts
  - cat $HOME/.ssh/known_hosts

before_deploy:
- openssl aes-256-cbc -K $encrypted_deploy_key -iv $encrypted_deploy_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa

cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn install
  - yarn test
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  script: scp -p 5022 /build web@www.lawbot.io:~/build
  on:
    branch: master
