language: node_js
node_js:
- 8.9.4
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_b6e2e769a5bd_key -iv $encrypted_b6e2e769a5bd_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa

before_script:
  - echo -e "Host www.lawbot.io\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn test
- yarn build
deploy:
  provider: script
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  script: 
    scp -P 5022 -r build web@www.lawbot.io:/home/web/lawtalk_news;
    ssh -p 5022 web@www.lawbot.io "sudo docker-compose -f ./lawtalk_news/docker-compose.yml down && sudo docker-compose -f ./lawtalk_news/docker-compose.yml up -d"
  on:
    branch: master
