language: node_js
node_js:
  - "8.9.4"

addons:
  yarn: 1.7.0
cache:
  directories:
  - node_modules
script:
  - yarn test --watchAll
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master


