language: node_js
node_js:
  - "8.9.4"

cache:
  directories:
  - node_modules
script:
  # - yarn test --watchAll
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master


